# Generated by Django 2.1.7 on 2019-03-21 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20190321_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='owner',
            new_name='user',
        ),
    ]
